### ISSUE TITLE
Error building environment for Binder

### ISSUE THREAD

**Issue by kafitzgerald** [ProjectPythia/advanced-viz-cookbook#82]
Haven't had time to diagnose this, but when I try to launch via Binder I'm getting an error:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/srv/conda/lib/python3.11/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/srv/conda/lib/python3.11/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/srv/conda/lib/python3.11/site-packages/conda/notices/core.py", line 109, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/srv/conda/lib/python3.11/site-packages/conda_env/cli/main_update.py", line 132, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/srv/conda/lib/python3.11/site-packages/mamba/mamba_env.py", line 153, in mamba_install
        transaction.fetch_extract_packages()
    RuntimeError: Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/linux-64/lerc-4.0.0-h27087fc_0.tar.bz2]
    Connection timed out after 9058 milliseconds

`$ /srv/conda/bin/mamba update -p /srv/conda/envs/notebook --file environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=/srv/conda/envs/notebook
                CONDA_DIR=/srv/conda
           CONDA_PLATFORM=linux-64
               CONDA_ROOT=/srv/conda
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/jovyan/.local/bin:/home/jovyan/.local/bin:/srv/conda/envs/notebo
                          ok/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr
                          /sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/jovyan/.condarc
 populated config files : /srv/conda/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.11.11.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.27=0
                          __linux=6.5.0=0
                          __unix=0=0
       base environment : /srv/conda  (writable)
      conda av data dir : /srv/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /srv/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /srv/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.32.3 CPython/3.11.11 Linux/6.5.0-35-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

P'��"]Ph��"]9eaf8c_0.conda extraction failed
error    libmamba Error when extracting package: [json.exception.type_error.316] invalid UTF-8 byte at index 3: 0x9C
error    libmamba Error when extracting package: std::bad_alloc
����"]��"]300_2.conda extraction failed
```

**Comment by kafitzgerald** [comment]
It looks like Anaconda is investigating "in timeouts affecting anaconda.org" ([see here](https://anaconda.statuspage.io/)).  I wonder if this is what we're hitting with the download error / timeout.

**Comment by kafitzgerald** [comment]
If we're looking to thin down the environment these might be some packages to look at:

```
 20M	../advanced-viz-cookbook/lib/python3.12/site-packages/jupyterlab
 22M	../advanced-viz-cookbook/lib/python3.12/site-packages/pyarrow
 23M	../advanced-viz-cookbook/lib/python3.12/site-packages/holoviews
 27M	../advanced-viz-cookbook/lib/python3.12/site-packages/datashader
 28M	../advanced-viz-cookbook/lib/python3.12/site-packages/matplotlib
 29M	../advanced-viz-cookbook/lib/python3.12/site-packages/numba
 31M	../advanced-viz-cookbook/lib/python3.12/site-packages/babel
 31M	../advanced-viz-cookbook/lib/python3.12/site-packages/numpy
 37M	../advanced-viz-cookbook/lib/python3.12/site-packages/bokeh
 50M	../advanced-viz-cookbook/lib/python3.12/site-packages/sklearn
 52M	../advanced-viz-cookbook/lib/python3.12/site-packages/statsmodels
 64M	../advanced-viz-cookbook/lib/python3.12/site-packages/scipy
 71M	../advanced-viz-cookbook/lib/python3.12/site-packages/pandas
110M	../advanced-viz-cookbook/lib/python3.12/site-packages/panel
174M	../advanced-viz-cookbook/lib/python3.12/site-packages/plotly
```

**Comment by kafitzgerald** [comment]
Seems to be resolved now.
